name: Run with example repository

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Gradle
      run: ./gradlew --init-script=./scripts/disableSign.init.gradle publishToMavenLocal

    - uses: actions/upload-artifact@v2
      with:
        name: maven-repository
        path: ~/.m2/repository

  example-run:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gradle: ["4.0", "7.0"]
        setting:
          - clean # just build
          - setupDecompWorkspace
          - setupDevWorkspace
          - setupCiWorkspace
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/download-artifact@v2
        with:
          name: maven-repository
          path: ~/.m2/repository

      - name: Setup Gradle Wrapper
        run: |
          touch empty
          ./gradlew --build-file=empty wrapper --gradle-version=${{ matrix.gradle }}
          ./gradlew --build-file=empty wrapper
          rm empty

      - name: Run Setup Task
        run: |
          cd example
          ./gradlew --init-script=../scripts/useLocal.init.gradle ${{ matrix.setting }}

      - name: Run Build Task
        run: |
          cd example
          ./gradlew --init-script=../scripts/useLocal.init.gradle build
